<?php
$data = array (
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '时尚精品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 0,
    'id' => '5',
    'name' => '时尚精品',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '休闲运动',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '休闲运动',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '生活用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '生活用品',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '电子产品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 2,
    'level' => 0,
    'id' => '2',
    'name' => '电子产品',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '图书',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '1',
    'name' => '图书',
  ),
);
?>